name: Scraping Anime Data

on:
  push:
    branches:
      - main  # Peut être 'master' selon ton dépôt
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit

jobs:
  scraping:
    runs-on: ubuntu-latest  # Utilisation d'une machine Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout du code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Assure-toi que la version de Python est correcte

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installer les dépendances

      - name: Run scraping script
        run: |
          python scraper.py  # Exécute ton script Python

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add animes.json  # Ajoute le fichier généré
          git commit -m "Ajout des résultats du scraping" || echo "Aucun changement à committer"  # Commit du fichier
          git push https://github.com/Stephenson-alvaro/animes_sama.git HEAD:main  # Pousse les changements sur la branche main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
