name: Scraper Anime Catalogue

on:
  workflow_dispatch:  # Permet de lancer manuellement
  push:
    paths:
      - scrape.py

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Utiliser la version de Python que tu souhaites

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4
          playwright install chromium

      - name: Run scraper
        run: |
          python scraper.py  # Exécute ton script scraper.py

      - name: Ajouter le fichier JSON et committer
        run: |
          # Ajoute et commite le fichier JSON généré par le scraper
          git add animes.json  # Le fichier JSON généré par ton script
          git commit -m "Ajout des données scrappées"
          git push
