name: Scraping Anime Data

on:
  push:
    branches:
      - main  # Peut être 'master' selon ton dépôt
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit

jobs:
  scraping:
    runs-on: ubuntu-latest  # Utilisation d'une machine Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout du code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Assure-toi que la version de Python est correcte

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installer les dépendances

      - name: Supprimer l'ancien fichier JSON
        run: |
          if [ -f "animes.json" ]; then
            rm animes.json
          fi

      - name: Run scraping script
        run: |
          python scraper.py  # Exécute ton script Python

      - name: Configurer Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Enregistrer les données dans le dépôt
        run: |
          git add animes.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour des données d'anime"
          git push
